### ISSUE TITLE
Vue: Module '@padcom/vue-i18n' has no exported member i18n

### ISSUE THREAD

**Issue by doic-ai** [padcom/vue-i18n#1]
When following [your readme](https://github.com/padcom/vue-i18n?tab=readme-ov-file#for-applications), I encountered this error:
`Vue: Module '@padcom/vue-i18n' has no exported member i18n`
Is the readme up to date ?

**Comment by padcom** [comment]
Hi! In point of fact it might have gone out of date. I'll update it. Thanks for giving this library a try!

**Comment by padcom** [comment]
In the meantime you can check out the following 2 examples for Vue 2 and 3:

https://github.com/padcom/vue-i18n-example-vue2
https://github.com/padcom/vue-i18n-example-vue3

**Comment by padcom** [comment]
The docs have been updated. Please let me know if you have any questions or if the updated docs are good enough for you. Also don't forget to check out the working examples :)

**Comment by doic-ai** [comment]
Thanks! I went with version 0.1.0 but I'll check the update very soon 😄

**Comment by doic-ai** [comment]
When using Typescript in vite.config.ts, you need to pass an empty object to plugin because it expects one argument.

```typescript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import i18n from '@padcom/vite-plugin-vue-i18n'

export default defineConfig({
  plugins: [
    vue(),
    i18n( {} ) , // <== here
  ]
})```

**Comment by padcom** [comment]
Could you make a separate ticket for that?
