### ISSUE TITLE
Using useI8n from composable

### ISSUE THREAD

**Issue by doic-ai** [padcom/vue-i18n#3]
Hello

I'm trying as hard as I can to use my own composable which imports useI18n from here.

When I do so, I get
`Error: vue-i18n not initialized. Either call createI18n() or createI18nContext()`

I obviously have a `createI18nContext()` at the root of my web component.

It seems importing createI18nContext from '@padcom/vue-i18n' at the root, and importing useI18n from '@/composables/...' in my child components can't be done.

Is there a way to do so, or should the lib be modified ?

I need to use my own composable because I force the type of the t() first parameter, in order to have errors when there is no corresponding translation key.

I get the error even if my composable returns use18n without changing it...

**Comment by padcom** [comment]
Could you create a small project that reproduces the problem? That'll help a lot in figuring things out

**Comment by doic-ai** [comment]
Actually, it works fine on the small project, so there may be a conflict in mine, that I can't get to see.
Thanks, it actually helped !

**Comment by padcom** [comment]
The only thing I can think of at the moment that could cause the problem you have described is that the injection keys from library are not registered. They are exported from the library so if you `provide()` them, everything should work just fine. I make no distinction between externally provided and from-library provided instances.

**Comment by doic-ai** [comment]
OK, I'll look into it

**Comment by padcom** [comment]
https://github.com/padcom/vue-i18n/blob/master/packages/vue/index.ts#L131

There are 4 of them, so if you'd like to use the lib from a web component either call the `createI18nContext()` or inject them yourself. Although I can't see a reason why you should use the `createI18nContext()` and just wrap the `useI18n()` in a function that provides more type checking for the keys. That should give you best of both worlds with the least effort.
